### ISSUE TITLE
demux custom sample sheet: preserve file extension

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#12]
demux applet with custom sample sheet fails for anything other than .txt files. It looks like this might already be fixed?

**Comment by yifei-men** [comment]
This should be fixed in https://github.com/dnanexus/viral-ngs/commit/ed446975dde454002bbeaa72c00012cd38fb9fe0

But I'll leave this open until we merge the commit into our `dnanexus` master.

**Comment by yifei-men** [comment]
Addressed by #20
