### ISSUE TITLE
increase instance size for depletion applet

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#15]
Currently, depletion defaults to a mem3_hdd2_x4. Can we change this to a mem1_ssd1_x32 or perhaps a mem1_ssd1_x8? Now that our depletion code (in v1.5.0) has better runtime scalability and threads better (please pass it a --threads parameter proportional to instance size), it would be nice to increase the instance to a size that also has better network performance. The mem3_hdd2_x4 seems to take about 15 mins to download the depletion databases before executing code. If I'm translating your instance types to EC2 types properly, I think a mem1_ssd1_x8 offers "high" network connectivity and the _x32 offers 10Gb.

**Comment by yifei-men** [comment]
> If I'm translating your instance types to EC2 types properly, I think a mem1_ssd1_x8 offers "high" network connectivity and the _x32 offers 10Gb.

I believe the mem1_ssd1 instances do offer better connectivity, especially for the 32 core ones, so we should see some improvements

Need to be unblocked by #11

**Comment by yifei-men** [comment]
Addressed by #20
