### ISSUE TITLE
demux applet on tarballs

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#16]
Allow the demux applet to operate on a list of tarballs instead of a sentinel file, for greater portability to applications where users upload their own data (instead of utilizing the streaming uploader).

**Comment by yifei-men** [comment]
This should be addressed in https://github.com/dnanexus/viral-ngs/commit/3a6ab0539895160a22ee2f23d65568ff8bb0fdb6

But again, I'll leave this open until it's merged into `dnanexus`, and KIV a CI test.

Edit 6/20: CI test addressed by https://github.com/dnanexus/viral-ngs/commit/9e57b06919638a3af0db6a465ab2250200ceed7b

**Comment by yifei-men** [comment]
Addressed by #20
