### ISSUE TITLE
higher default retry count for streaming uploader

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#17]
Current retry count is 3, increase to a higher number by default? @tomkinsc can comment on specifics

**Comment by tomkinsc** [comment]
I opened a separate issue for this on the uploader repo:
https://github.com/dnanexus-rnd/dx-streaming-upload/issues/7

**Comment by yifei-men** [comment]
Closing this in favor of the issue on `dx-streaming-upload`
