### ISSUE TITLE
Include barcode frequency report among those generated during demux

### ISSUE THREAD

**Issue by tomkinsc** [dnanexus/viral-ngs#27]
A new sub-command, `common_barcodes`, [has been added](https://github.com/broadinstitute/viral-ngs/pull/384/files) to `viral-ngs/illumina.py`. This command writes a report listing the barcodes present in a sequencer run, sorted by frequency in descending order. The information is helpful for troubleshooting whether or not a barcode may have been entered incorrectly in the original sample sheet.

This command will be available in the next release of viral-ngs.

It would be helpful to add a call to this command to the demultiplexing applet, so the barcode report is among those generated by that step.

**Comment by tomkinsc** [comment]
This has been refactored a bit. While the aforementioned command still exists, the same report can now be created by specifying the `--commonBarcodes` argument to `illumina_demux` (it's the path of the file to write with the barcode counts).

**Comment by yifei-men** [comment]
Thanks @tomkinsc for the headsup

Note to self: Update resource tarball to next tag release.. 1.5.6 (?) and test with `--commonBarcodes <barcode_report_fn>` argument

**Comment by yifei-men** [comment]
Note to self: function included in upstream v1.6.0 release

**Comment by yifei-men** [comment]
Addressed by #30
