### ISSUE TITLE
update kraken database

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#29]
We've updated the Kraken database to include a few more taxa:

https://storage.googleapis.com/sabeti-public/meta_dbs/kraken_ercc_db_20160705.tar.lz4

Can you update the workflow to utilize this one?

**Comment by tomkinsc** [comment]
The lz4 database is not yet uploaded, but it will be soon!

**Comment by yifei-men** [comment]
@tomkinsc seems like it's up now, fetching 😄

**Comment by yifei-men** [comment]
Addressed by #30
