### ISSUE TITLE
assembly process names output files funny

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#37]
Not sure what version this started at, but it seems that the final (non-intermediate) output files of the Generic assembly pipeline are <samplename>.scaffold.<extensions>. That is, for some reason, "scaffold" is now appended to the sample names during assembly. Can we remove that? Obviously this is kind of lower priority / aesthetic.

**Comment by yifei-men** [comment]
Closed via #39

the `.scaffold` suffix is now removed from intermediate files generated in the refinement and analysis steps.
