### ISSUE TITLE
index mapped bam files

### ISSUE THREAD

**Issue by tomkinsc** [dnanexus/viral-ngs#38]
It would be nice if the applets that return aligned `.bam` files would also run `samtools index` on the files to create an index `.bai` file for each `.bam`. This would allow users to visualize the output in the DNAnexus version of IGV.

**Comment by yifei-men** [comment]
Hey Chris, I'm adding the bam index output in `analysis` step [here](https://github.com/dnanexus/viral-ngs/blob/v1.8.0-updates/viral-ngs-assembly-analysis/src/code.sh#L47).... which gives the aligned reads against the final assembly.

Is there any other steps / aligned bam files that you would like a `.bai` output?

(I'm being lazy and not reasoning about whether each of the bam file output is aligned / unaligned)

**Comment by tomkinsc** [comment]
That's the main one people would care about, so it's a good place to start. If users request the ability to view other bam files in IGV, I can open new issues.

**Comment by yifei-men** [comment]
Closed via #39
