### ISSUE TITLE
reduce scaffolding params default values

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#43]
For scaffolding, our own default practice has been to significantly lower the min_length_fraction and min_unambig cutoffs to 0.5 for each. This just reduces the number of jobs that hit a PoorAssemblyError and allows for more partial genomes to come out the analysis.

**Comment by tomkinsc** [comment]
The relevant lines are here: 
https://github.com/dnanexus/viral-ngs/blob/dnanexus/viral-ngs-assembly-scaffolding/dxapp.json#L44-L54

**Comment by dpark01** [comment]
Looks like I accidentally fixed this one already
