### ISSUE TITLE
pass --threads param to refine_assembly invocations

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#46]
In the refine1 and refine2 stages of the various viral-ngs workflows, it appears that `assembly.py refine_assembly` is being called without `--threads`, which causes it to default to single threaded mode. Can you pass it a value equal to the instance's core count (keeping in mind that users may manually request a different instance size sometimes)?

**Comment by mlin** [comment]
@dpark01 @tomkinsc have you had any opportunity to verify this works?

**Comment by tomkinsc** [comment]
I tried running a test assembly, and the `--threads` parameter appears to have been passed correctly to both invocations of `refine_assembly`.
