### ISSUE TITLE
expose --major_cutoff in refine_assembly

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#48]
Expose the `--major_cutoff` parameter (it's relatively new in viral-ngs) in both of the refine1 and refine2 assembly steps. Default to null/not specified, but optionally some floating point value between 0 and 1.

**Comment by mlin** [comment]
@dpark01 updated the featured project with 4ef5a0c. If you set major_cutoff in the first refinement stage, by default the same setting will propagate to the second refinement stage (but they can be overridden separately)

**Comment by dpark01** [comment]
Excellent thanks!
