### ISSUE TITLE
scale back deplete instance size

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#57]
Looking at the logs in our deplete executions, it looks to be horribly utilizing the resources we're giving it. It's currently getting a pricey mem3_x16, but it never seems to use more than 12GB RAM, 2 cores at best, maybe about 80GB disk.

Until we figure out how to parallelize better on our end, can you change this instance to a mem1_ssd1_x8 or mem2_ssd1_x4 or whatever seems economical?

**Comment by mlin** [comment]
OK; FWIW I think the actual blastn runs parallelize nicely; it's RevertSam+FilterSamReads+SamToFastq that spin 1-2 threads for hours on end (on HiSeq runs)
